import { sqliteTable, text, integer, index } from 'drizzle-orm/sqlite-core';
export const members = sqliteTable('members',{userId:text('user_id').primaryKey(),role:text('role').notNull(),displayName:text('display_name').notNull(),createdAt:integer('created_at').notNull()});
export const settings = sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const posts = sqliteTable('posts',{id:text('id').primaryKey(),slug:text('slug').notNull().unique(),draft:text('draft').notNull(),published:text('published'),version:integer('version').notNull().default(1),archived:integer('archived').notNull().default(0),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull(),publishedAt:integer('published_at')});
export const media = sqliteTable('media',{id:text('id').primaryKey(),objectKey:text('object_key').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),createdAt:integer('created_at').notNull()});
export const trackingLinks = sqliteTable('tracking_links',{id:text('id').primaryKey(),label:text('label').notNull(),destination:text('destination').notNull(),createdAt:integer('created_at').notNull()});
export const visitors = sqliteTable('visitors',{id:text('id').primaryKey(),displayName:text('display_name'),kind:text('kind').notNull(),firstSeen:integer('first_seen').notNull(),lastSeen:integer('last_seen').notNull()});
export const sessions = sqliteTable('sessions',{id:text('id').primaryKey(),visitorId:text('visitor_id').notNull(),startedAt:integer('started_at').notNull(),lastAt:integer('last_at').notNull(),entryPath:text('entry_path').notNull(),language:text('language').notNull(),device:text('device').notNull(),referrer:text('referrer'),linkId:text('link_id'),internal:integer('internal').notNull().default(0)},t=>[index('sessions_time').on(t.startedAt),index('sessions_visitor').on(t.visitorId)]);
export const events = sqliteTable('events',{id:text('id').primaryKey(),sessionId:text('session_id').notNull(),visitorId:text('visitor_id').notNull(),occurredAt:integer('occurred_at').notNull(),receivedAt:integer('received_at').notNull(),type:text('type').notNull(),page:text('page').notNull(),ctaId:text('cta_id'),label:text('label'),target:text('target'),language:text('language').notNull(),branch:text('branch')},t=>[index('events_time').on(t.occurredAt),index('events_session').on(t.sessionId),index('events_visitor').on(t.visitorId)]);
