import fs from 'node:fs';
import { collarSection } from './additions.mjs';
import { memberViews } from './members.mjs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'site-pages');
const publicDir=path.join(root,'public');
fs.mkdirSync(out,{recursive:true});
fs.cpSync(path.join(root,'site'),publicDir,{recursive:true});
const read = name => JSON.parse(fs.readFileSync(path.join(root, 'content', name + '.json'), 'utf8'));
const cats = read('cats'), events = read('events'), partners = read('partners');
const strings = {};
let stringIndex = 0;
const esc = value => String(value).replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
function t(vi, en) {
  const key = 's' + stringIndex++;
  strings[key] = {vi, en};
  return `<span data-i18n="${key}">${vi}</span>`;
}
const tt = pair => t(pair.vi, pair.en);
const arrow = '<svg class="arrow" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const paw = '<svg class="paw" viewBox="0 0 48 48" aria-hidden="true"><ellipse cx="13" cy="16" rx="5" ry="7" transform="rotate(-27 13 16)"/><ellipse cx="23" cy="10" rx="5" ry="7"/><ellipse cx="34" cy="14" rx="5" ry="7" transform="rotate(23 34 14)"/><ellipse cx="40" cy="25" rx="4" ry="6" transform="rotate(32 40 25)"/><path d="M12 34c1-7 7-14 13-13s11 9 11 16-7 7-12 4-14 0-12-7Z"/></svg>';
const catDrawing = '<svg class="cat-drawing" viewBox="0 0 220 220" fill="none" aria-hidden="true"><path d="m56 102-5-57 43 26a79 79 0 0 1 39 0l39-26-3 62c26 59-4 82-56 82S29 165 56 102Z" fill="currentColor"/><path d="m76 120 10 4m51 0 10-4m-42 17 9 6 9-6m-9 7v10m0 0c-10 10-16 1-16 1m16-1c10 10 16 1 16 1" stroke="var(--cream)" stroke-width="5" stroke-linecap="round"/><path d="m34 134 31 5m-34 11 34-1m90-9 31-7m-32 17 35 1" stroke="currentColor" stroke-width="4" stroke-linecap="round"/></svg>';
const branches = [
  {slug:'tan-phu',short:'Tân Phú',name:'AEON Tân Phú',no:'01',image:'branch-tan-phu.jpg',fallback:'together.jpg',label:{vi:'Một góc mèo trong AEON.',en:'A little cat corner at AEON.'},address:{vi:'Tầng trệt · Cổng L2 · PETEMO<br>30 Tân Thắng, TP. Hồ Chí Minh',en:'Ground floor · Gate L2 · PETEMO<br>30 Tân Thắng, Ho Chi Minh City'},price:{vi:'109.000đ · tất cả các ngày',en:'109,000 VND · every day'},note:{vi:'Ghé CATFE sau một vòng dạo AEON. Chọn một chỗ ngồi, nghe hướng dẫn của nhân viên và để buổi làm quen bắt đầu.',en:'Make CATFE part of your AEON visit. Find a seat, follow the team’s guidance and settle into a little cat company.'},map:'CATFE AEON MALL Tan Phu'},
  {slug:'binh-tan',short:'Bình Tân',name:'AEON Bình Tân',no:'02',image:'branch-binh-tan.jpg',fallback:'hero.jpg',label:{vi:'Đi dạo một vòng. Ghé mèo một chút.',en:'A little shopping. A little cat company.'},address:{vi:'Tầng trệt · G19A · PETEMO · Cổng 10<br>1 Đường số 17A, TP. Hồ Chí Minh',en:'Ground floor · G19A · PETEMO · Gate 10<br>1 Đường số 17A, Ho Chi Minh City'},price:{vi:'109.000đ · tất cả các ngày',en:'109,000 VND · every day'},note:{vi:'Nhà Bình Tân nằm trong khu PETEMO, tầng trệt AEON MALL. Nhắn CATFE trước nếu bạn đi cùng nhóm hoặc cần hỏi thêm về chuyến ghé.',en:'Find the Bình Tân home inside PETEMO on the ground floor of AEON MALL. Message the team about group visits or anything you need to plan ahead.'},map:'CATFE AEON MALL Binh Tan'},
  {slug:'estella',short:'Estella',name:'Estella Place',no:'03',image:'branch-estella.jpg',fallback:'cuddles.jpg',label:{vi:'Một buổi hẹn ở phía Đông thành phố.',en:'Your cat date on the east side.'},address:{vi:'Tầng trệt · Góc bên trái Estella Place<br>88 Song Hành, TP. Hồ Chí Minh',en:'Ground floor · Left side of Estella Place<br>88 Song Hành, Ho Chi Minh City'},price:{vi:'109.000đ ngày thường · 119.000đ cuối tuần',en:'109,000 VND weekdays · 119,000 VND weekends'},note:{vi:'Tìm CATFE ở tầng trệt Estella Place. Một chỗ dừng chân cho buổi hẹn với mèo, sau khi bạn đã chọn được nhịp riêng của mình.',en:'Find CATFE on the ground floor of Estella Place. A place to pause, settle in and let the cats set the pace.'},map:'CATFE Estella Place 88 Song Hanh'}
];
const stories = [
  {slug:'chiec-ao-vit',image:'mischief.jpg',category:{vi:'MỘT CHÚT TINH NGHỊCH',en:'A LITTLE MISCHIEF'},title:{vi:'Mèo đây. Vịt là áo thôi.',en:'Still a cat. Just dressed as a duck.'},excerpt:{vi:'Một chiếc áo vàng. Một gương mặt rất mèo. Có những khoảnh khắc dễ thương chẳng cần kể thêm.',en:'A yellow outfit. An unmistakably feline face. Some little moments speak for themselves.'},paragraphs:[{vi:'Trong bức ảnh từ CATFE, bộ đồ vịt màu vàng chiếm gần hết khung hình. Nhưng thứ khiến mình dừng lại là gương mặt ló ra phía dưới: vẫn rất mèo.',en:'In this CATFE photograph, a yellow duck outfit almost fills the frame. Then you notice the little face underneath: unmistakably a cat.'},{vi:'Một nét mặt, một dáng ngồi, một lần ngước nhìn. Đôi khi điều mình nhớ sau chuyến ghé lại nhỏ xíu như vậy.',en:'An expression, a way of sitting, a glance upward. Sometimes the thing you remember from a visit is that small.'},{vi:'Ảnh kể một khoảnh khắc. Lần ghé của bạn sẽ có nhịp riêng — cứ ngồi lại, quan sát và làm quen với các bé theo hướng dẫn của nhân viên.',en:'A photograph holds one moment. Your visit will have its own rhythm. Settle in, observe and follow the team’s guidance as you meet the cats.'}]},
  {slug:'mot-loi-chao-cham',image:'together.jpg',category:{vi:'NHỮNG LẦN LÀM QUEN',en:'LITTLE CONNECTIONS'},title:{vi:'Có khi, ngồi cạnh đã là làm quen.',en:'Sometimes, sitting nearby is a hello.'},excerpt:{vi:'Không phải lần làm quen nào cũng bắt đầu bằng một cái bế. Chừa một chút khoảng trống cho bé chọn.',en:'A connection needn’t begin with a cuddle. Leave a little space for the cat to choose.'},paragraphs:[{vi:'Một bé mèo nằm gần chỗ ngồi. Bạn nhìn sang. Bé nhìn lại, hoặc tiếp tục ngủ. Cả hai đều có thể là một phần bình thường của buổi ghé.',en:'A cat rests near your seat. You glance over. They might look back, or carry on sleeping. Either can be part of an ordinary café visit.'},{vi:'Ở CATFE, màu vòng cổ giúp khách hiểu nhóm tuổi và những bé cần được tiếp cận nhẹ nhàng hơn. Nhân viên sẽ giúp bạn đọc những dấu hiệu đó.',en:'At CATFE, collar colours help visitors understand age groups and cats who need a gentler approach. The team can help you interpret those cues.'},{vi:'Bạn có thể chơi theo hướng dẫn, ngồi yên hoặc chỉ quan sát. Điều đáng nhớ không nhất thiết phải là một cái ôm — mà là lúc bé thấy đủ thoải mái để ở gần.',en:'You can play with guidance, sit quietly or simply watch. A memorable moment needn’t be an embrace. It can be a cat feeling comfortable nearby.'}]},
  {slug:'mot-mai-nha-lau-dai',image:'hero.jpg',category:{vi:'THƯƠNG MÈO LÂU DÀI',en:'CARE THAT CONTINUES'},title:{vi:'Một mái nhà, cả lúc đã già.',en:'A home, through the quieter years.'},excerpt:{vi:'Có những bé đã lớn lên cùng CATFE. Việc chăm sóc tiếp tục, cả khi nhịp sống của bé chậm lại.',en:'Some cats have grown up with CATFE. Their care continues as their pace becomes gentler.'},paragraphs:[{vi:'CATFE bắt đầu từ năm 2016. Theo câu chuyện CATFE công bố, có những thành viên đã lớn lên và già đi cùng ngôi nhà này.',en:'CATFE began in 2016. In its published story, CATFE describes residents who have grown up and grown older within this home.'},{vi:'Trong thông báo đóng chi nhánh Quận 1, CATFE nói về việc tiếp tục chăm sóc những bé lớn tuổi đến cuối đời. Một địa điểm có thể thay đổi; trách nhiệm với các bé vẫn tiếp tục.',en:'In its District 1 closure announcement, CATFE describes continuing to care for its older cats throughout their lives. A location may change; that responsibility continues.'},{vi:'Với khách ghé chơi, thương mèo cũng có thể là nhẹ tay hơn, nói khẽ hơn và để một giấc ngủ được trọn vẹn. Mỗi giai đoạn sống cần một cách quan tâm khác nhau.',en:'For visitors, care can mean gentler hands, quieter voices and leaving a nap undisturbed. Every stage of a cat’s life deserves a thoughtful approach.'}],source:'https://www.catfe.vn/vi/tin-tuc/thong-bao-dong-cua-catfe-quan-1-tu-01032026.html'}
];
const faqs = [
  ['Giá vé bao nhiêu?','How much is a ticket?','AEON Tân Phú và AEON Bình Tân: 109.000đ/người. Estella Place: 109.000đ từ thứ Hai đến thứ Sáu; 119.000đ thứ Bảy và Chủ nhật. Nhắn nhà bạn chọn để xác nhận giá dịp lễ, Tết.','AEON Tân Phú and AEON Bình Tân: 109,000 VND per guest. Estella Place: 109,000 VND Monday–Friday; 119,000 VND Saturday–Sunday. Confirm holiday pricing with your chosen location.'],
  ['Vé đã gồm những gì?','What does the ticket include?','Vé gồm khu vực chơi cùng mèo, buffet đồ ăn vặt và nước uống. Theo thông tin CATFE công bố, không giới hạn thời gian trong giờ hoạt động.','Your ticket includes the cat area, the snack and drink buffet, and no time limit during café hours, according to CATFE’s published information.'],
  ['Các nhà mở cửa lúc mấy giờ?','What are the café hours?','Giờ CATFE công bố cho ba chi nhánh là 10:00–21:30. Vào dịp lễ hoặc khi đi cùng nhóm, bạn nên nhắn quán trước chuyến ghé.','CATFE lists 10:00–21:30 for all three locations. Message the café before holiday or group visits.'],
  ['Có cần đặt trước không?','Should I arrange my visit in advance?','Bạn có thể nhắn CATFE qua Facebook hoặc Zalo để hỏi tình trạng chỗ, đặc biệt vào cuối tuần và khi đi theo nhóm. Nhân viên sẽ xác nhận trực tiếp.','Message CATFE on Facebook or Zalo about availability, especially for weekends and groups. The team will confirm arrangements directly.'],
  ['Có được bế mèo không?','May I hold the cats?','Hỏi nhân viên trước, nhìn màu vòng cổ và quan sát phản ứng của bé. Không cố bế mèo đang ngủ, ăn, tránh né hoặc tỏ ra không thoải mái. Ngồi cạnh và chơi theo hướng dẫn cũng là cách làm quen.','Ask the team, notice the collar colour and watch the cat’s response. Avoid lifting a cat who is sleeping, eating, moving away or uncomfortable. Sitting nearby and guided play are ways to connect, too.'],
  ['Vì sao có bé ngủ khi khách tới?','Why might a cat be asleep during my visit?','Mỗi bé có nhịp sinh hoạt và nhu cầu nghỉ riêng. Nếu bé đang ngủ, để bé nghỉ nhé. Nhân viên có thể chỉ bạn những bé đang thức và phù hợp để tương tác.','Each cat has its own rhythm and need for rest. Let a sleeping cat rest. The team can help you meet residents who are awake and comfortable with interaction.'],
  ['Mèo có được tiêm phòng không?','Are the cats vaccinated?','Bạn hãy hỏi trực tiếp nhân viên tại nhà mình định ghé để được xác nhận thông tin chăm sóc và tiêm phòng hiện hành. Nếu cần thông tin cụ thể cho một bé, nhờ nhân viên hỗ trợ trước khi tương tác.','Ask your chosen location for its current care and vaccination information. If you need details about a particular cat, ask the team before interacting.'],
  ['Trẻ nhỏ có thể ghé không?','May children visit?','Nhắn chi nhánh trước để hỏi chính sách theo độ tuổi và việc giám sát. Người lớn cần giúp trẻ nói khẽ, chạm nhẹ, không rượt đuổi và để mèo được nghỉ.','Contact your location about age and supervision policies. Adults should guide children to speak softly, touch gently, avoid chasing and let cats rest.']
];

let currentPage = '';
function url(target='') {const relative=path.posix.relative(path.posix.dirname(currentPage || 'index.html'), target || '.'); return relative ? relative + (target.endsWith('/') ? '/' : '') : './';}
function href(target='') {const value=url(target); return value === '' ? './' : value;}
const asset = name => href('assets/' + name);
function link(target,vi,en,cls='text-link') {return `<a class="${cls}" href="${esc(href(target))}">${t(vi,en)}${arrow}</a>`;}
function external(target,vi,en,cls='text-link'){return `<a class="${cls}" href="${esc(target)}" target="_blank" rel="noopener noreferrer">${t(vi,en)}${arrow}</a>`;}
function image(name,altVi,altEn,cls='',eager=false) {return `<img class="${cls}" src="${asset(name)}" alt="${esc(altVi)}" data-alt-vi="${esc(altVi)}" data-alt-en="${esc(altEn)}" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;}
const branchImage = b => fs.existsSync(path.join(publicDir,'assets',b.image)) ? b.image : b.fallback;
function eyebrow(vi,en){return `<p class="eyebrow">${t(vi,en)}</p>`;}
function sectionHeading(vi,en,subVi='',subEn=''){return `<div class="section-heading reveal">${eyebrow(subVi,subEn)}<h2>${t(vi,en)}</h2></div>`;}
const residents=memberViews({cats,t,tt,href,image,link,eyebrow,esc,arrow,paw,pageIntro});
function languageButtons(){return `<div class="language-switch" role="group" aria-label="Ngôn ngữ / Language"><button type="button" data-lang="vi" aria-pressed="true">VI</button><span aria-hidden="true">/</span><button type="button" data-lang="en" aria-pressed="false">EN</button></div>`;}
function header(){
 const items=[['','Trang chủ','Home'],['chuyen-catfe/','Chuyện CATFE','Our story'],['lan-dau-ghe/','Lần đầu ghé','First visit'],['events/','Events','Events'],['cac-nha/','Các nhà CATFE','Our homes'],['faq/','FAQ','FAQ']];
 const nav=items.map(([p,v,e])=>`<a ${((currentPage==='index.html'&&!p)||(p&&currentPage.startsWith(p)))?'aria-current="page"':''} href="${href(p)}">${t(v,e)}</a>`).join('');
 return `<a class="skip-link" href="#main">${t('Đến nội dung chính','Skip to content')}</a><header class="site-header"><a href="${href('')}" class="brand" aria-label="CATFE">${image('logo.png','CATFE — Cat & Coffee','CATFE — Cat & Coffee','brand-logo',true)}</a><nav class="desktop-nav" aria-label="Menu">${nav}</nav><div class="header-actions">${languageButtons()}${link('cac-nha/','Chọn nhà CATFE','Find your CATFE','button button-small header-cta')}<button class="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-menu" aria-label="Menu"><span></span><span></span></button></div><nav class="mobile-menu" id="mobile-menu" aria-label="Menu mobile" hidden>${nav}${link('cac-nha/','Chọn nhà CATFE','Find your CATFE','button')}</nav></header>`;
}
function footer(){return `<footer class="site-footer"><div class="footer-top wrap"><div class="footer-brand"><a href="${href('')}" aria-label="CATFE">${image('logo.png','CATFE — Cat & Coffee','CATFE — Cat & Coffee','footer-logo')}</a><p>${t('Thiên đường mèo.<br>Mỗi bé một tính. Mỗi lần ghé một niềm vui.','A little cat paradise.<br>Distinct personalities. Lovely little encounters.')}</p>${languageButtons()}</div><div class="footer-column"><h3>${t('Các nhà CATFE','Our homes')}</h3>${branches.map(b=>`<a href="${href(b.slug+'/')}">${b.name}</a>`).join('')}</div><div class="footer-column"><h3>${t('Khám phá','Explore')}</h3>${link('cac-nha/','Các bé của từng nhà','Meet each home’s cats','footer-link')}${link('chuyen-catfe/','Chuyện CATFE','CATFE stories','footer-link')}${link('events/','Events','Events','footer-link')}</div><div class="footer-column"><h3>${t('Thông tin','Plan a visit')}</h3>${link('lan-dau-ghe/','Lần đầu ghé','Your first visit','footer-link')}${link('faq/','FAQ','FAQ','footer-link')}${link('lan-dau-ghe/#collars','Màu vòng cổ','Collar colours','footer-link')}<a href="${href('quan-tri/')}" class="admin-entry">${t('Quản lý CATFE','CATFE studio')}</a><a href="tel:+84936908590">0936 90 85 90</a>${external('https://www.catfe.vn/','Thông tin từ CATFE','CATFE information','footer-link')}</div><div class="footer-column"><h3>Follow</h3>${external('https://www.facebook.com/catfevn/','Facebook','Facebook','footer-link')}${external('https://zalo.me/0936908590','Zalo','Zalo','footer-link')}${external('https://www.instagram.com/catfevn/','Instagram','Instagram','footer-link')}${external('https://www.tiktok.com/@catfe_cat_coffee','TikTok','TikTok','footer-link')}</div></div><div class="footer-bottom wrap"><span>© 2026 CATFE</span><span>${t('Vui vẻ. Hiểu mèo. Ấm áp.','Playful. Thoughtful. Warm.')}</span><button class="analytics-preferences" type="button">${t('Tùy chọn thống kê','Analytics preferences')}</button><button class="motion-toggle" type="button" aria-pressed="false">${t('Tạm dừng chuyển động','Pause motion')}</button><a class="back-top" href="#top" aria-label="Về đầu trang / Back to top">↑</a></div></footer>`;}
function closing(){return `<section class="closing"><div class="closing-visual">${image('hero.jpg','Một bé mèo CATFE đang ngước nhìn','A CATFE cat looking upward')}</div><div class="closing-copy reveal">${eyebrow('MỘT CUỘC HẸN NHỎ. MỘT LÝ DO QUAY LẠI.','A LITTLE CAT DATE. A REASON TO RETURN.')}<h2>${t('Hôm nay làm quen.<br><em>Lần sau, nhớ nhau.</em>','Meet today.<br><em>Remember each other.</em>')}</h2><p>${t('Hôm nay làm quen với một bé. Lần sau, có thể bạn quay lại vì chính bé đó.','Meet a cat today. Next time, they might be the very reason you return.')}</p>${link('cac-nha/','Chọn nhà CATFE','Find your CATFE','button button-cream')}${paw}</div></section>`;}
function reasons(){const cards=[['01','hero.jpg','Gặp một bé.<br>Làm quen một tính.','Meet a cat.<br>Discover a personality.','Có bé tò mò. Có bé thong thả. Ngồi lại một chút để nhận ra điều làm mỗi bé khác nhau.','Some are curious. Some take their time. Linger a little and discover what makes each cat distinct.'],['02','together.jpg','Có thời gian<br>để ở lại.','Time to<br>settle in.','Không giới hạn thời gian trong giờ hoạt động. Bạn có thể chờ một lời chào theo nhịp của mèo.','No time limit during café hours. You have time for a hello at the cat’s own pace.'],['03','mischief.jpg','Có một bé<br>để nhớ.','A little face<br>to remember.','Một ánh mắt, một trò nghịch, một nét riêng. Đôi khi lý do quay lại nhỏ xíu và có ria.','A glance, a playful moment, a little quirk. Sometimes a reason to return has whiskers.']];return `<section class="section reasons wrap" id="reasons">${sectionHeading('Ba lý do nhỏ.<br><em>Một buổi thật dễ thương.</em>','Three little reasons.<br><em>One lovely afternoon.</em>','ĐẾN VÌ MÈO. Ở LẠI ĐỂ LÀM QUEN.','COME FOR THE CATS. STAY TO KNOW THEM.')}<div class="reason-grid">${cards.map(([n,img,hv,he,pv,pe])=>`<article class="reason-card reveal"><div class="reason-top"><span class="micro-number">${n}</span><div class="round-photo">${image(img,'Một khoảnh khắc tại CATFE','A moment at CATFE')}</div></div><h3>${t(hv,he)}</h3><p>${t(pv,pe)}</p></article>`).join('')}</div></section>`;}
function storyIntro(){return `<section class="story-intro" id="story"><div class="wrap story-split"><div class="story-image reveal"><div class="photo-arch">${image('cuddles.jpg','Một vị khách ngồi cùng mèo tại CATFE','A guest spending time with a cat at CATFE')}</div><span class="photo-note">${t('thương cả lúc bé cần yên.','love their quiet moments, too.')}</span>${paw}</div><div class="story-copy reveal">${eyebrow('CHUYỆN CỦA MỘT NGÔI NHÀ','A STORY ABOUT HOME')}<h2>${t('Có những bé<br><em>lớn lên cùng CATFE.</em>','Some cats<br><em>grow up with CATFE.</em>')}</h2><p class="lead">${t('Và có những bé đã già đi ở đây.','And some grow old here, too.')}</p><p>${t('CATFE không chỉ là nơi có nhiều mèo. Từ năm 2016, những lần gặp gỡ nối tiếp nhau — còn việc chăm sóc các bé vẫn tiếp tục.','CATFE is more than a room full of cats. Since 2016, visits have come and gone, while care for the cats continues.')}</p><p>${t('Hiểu khi nào bé muốn chơi, khi nào cần nghỉ. Nhẹ nhàng với mỗi tính cách. Và tiếp tục ở bên khi những bước chân đã chậm hơn.','Knowing when a cat wants to play and when they need rest. Respecting different personalities. Staying alongside them as their steps become gentler.')}</p>${link('chuyen-catfe/','Đọc chuyện CATFE','Read our story')}</div></div></section>`;}
function proof(){return `<section class="proof-strip"><div class="wrap proof-grid"><div class="reveal"><strong>2016</strong><span>${t('Năm một mái nhà bắt đầu','The year our home began')}</span></div><div class="reveal"><strong>03</strong><span>${t('Nhà CATFE tại Sài Gòn','CATFE homes in Saigon')}</span></div><div class="reveal"><strong>∞</strong><span>${t('Không giới hạn thời gian ghé*','No time limit on your visit*')}</span></div></div><p class="proof-note">${t('*Trong giờ hoạt động · Buffet đã gồm trong vé','*During café hours · Snacks and drinks included')}</p></section>`;}
function steps(){const items=[['Chọn nhà.','Pick a home.','Tân Phú, Bình Tân hay Estella — chọn nơi thuận tiện cho bạn.','Tân Phú, Bình Tân or Estella — choose a place that suits you.'],['Xem giờ & thông tin.','Plan your visit.','Xem vé, giờ đón khách. Nhắn quán nếu đi theo nhóm.','Read ticket details and café hours. Message the team for group visits.'],['Nghe hướng dẫn.','Meet the team.','Nhân viên giúp bạn hiểu màu vòng cổ và cách làm quen.','The team explains collar colours and how to approach the cats.'],['Ngồi xuống. Làm quen.','Settle in. Say hello.','Để bé chủ động lại gần. Mình có thời gian mà.','Let a cat approach you. There’s time to become friends.']];return `<section class="section first-steps wrap" id="first-visit">${sectionHeading('Lần đầu ghé?<br><em>Cứ từ từ thôi.</em>','Your first visit?<br><em>Take it at cat pace.</em>','BỐN BƯỚC NHỎ, MỘT BUỔI DỄ CHỊU','FOUR LITTLE STEPS TO FEEL AT HOME')}<div class="steps-grid">${items.map((v,i)=>`<article class="step reveal"><span class="step-no">0${i+1}</span><h3>${t(v[0],v[1])}</h3><p>${t(v[2],v[3])}</p></article>`).join('')}</div><div class="gentle-note reveal">${paw}<p>${t('Không cần bế mới là làm quen. Có bé đang ngủ, có bé cần một khoảng riêng. Hãy để nhân viên chỉ bạn cách chào phù hợp.','A hello needn’t be a cuddle. Some cats are asleep; some need a little space. Let the team guide your first introduction.')}</p>${link('lan-dau-ghe/','Chuẩn bị cho buổi ghé','Before your visit')}</div></section>`;}
function locationCards(){return `<div class="location-grid">${branches.map(b=>`<article class="location-card reveal"><a class="location-image" href="${href(b.slug+'/')}">${image(branchImage(b),'Không gian và những khoảnh khắc CATFE '+b.name,'CATFE '+b.name+' café moments')}<span class="location-number">${b.no}</span><span class="image-caption">${t('nhà '+b.short,b.short+' home')}</span></a><div class="location-info"><h3><a href="${href(b.slug+'/')}">${b.name}</a></h3><p class="address">${tt(b.address)}</p><div class="location-facts"><span>10:00–21:30</span><span>${tt(b.price)}</span></div>${link(b.slug+'/','Xem nhà '+b.short,'Explore '+b.short,'button button-outline')}<a class="member-link" href="${href(b.slug+'/cats/')}" data-pending="${!(cats[b.slug]||[]).length}" aria-label="${esc('Gặp các bé '+b.short+((cats[b.slug]||[]).length?'':' — Coming soon'))}">${paw}${t('Gặp các bé '+b.short,'Meet the '+b.short+' cats')}${arrow}</a><small class="members-status">${(cats[b.slug]||[]).length?t(cats[b.slug].length+' gương mặt · Mỗi bé một tính',cats[b.slug].length+' little faces · Each a character'):t('Thành viên · Coming soon','Residents · Coming soon')}</small></div></article>`).join('')}</div>`;}
function locations(){return `<section class="section locations" id="locations"><div class="wrap"><div class="section-row">${sectionHeading('Ba nhà CATFE.<br><em>Bạn ghé nhà nào?</em>','Three CATFE homes.<br><em>Which one is yours?</em>','CHỌN MỘT NHÀ, GẶP NHỮNG GƯƠNG MẶT RIÊNG','CHOOSE A HOME. MEET ITS OWN LITTLE FAMILY.')}<p class="section-aside">${t('Xem thông tin từng nhà.<br>Rồi làm quen với các bé ở đó.','Explore each location.<br>Then meet the cats who live there.')}</p></div>${locationCards()}<p class="location-note">${t('Giá và giờ theo thông tin CATFE công bố. Nhắn quán trước chuyến ghé vào dịp lễ, Tết.','Prices and hours follow CATFE’s published information. Confirm holiday arrangements with the café.')}</p></div></section>`;}
function collars(){return collarSection(t,paw,external);}
function meet(){const items=[['eye','Quan sát trước.','Notice first.','Nhìn màu vòng cổ, tư thế và khoảng cách bé chọn.','Notice the collar colour, posture and distance the cat chooses.'],['wave','Chậm lại.','Take it slowly.','Nói khẽ, nhẹ tay. Hỏi nhân viên cách chơi phù hợp.','Quiet voices, gentle hands. Ask the team about suitable play.'],['paw','Để bé phản hồi.','Let them respond.','Bé lại gần thì làm quen. Bé tránh đi thì chừa khoảng riêng.','Say hello when a cat approaches. Give space if they move away.'],['moon','Tôn trọng lúc nghỉ.','Respect the nap.','Không đánh thức, rượt đuổi hoặc kéo bé khỏi chỗ trốn.','Avoid waking, chasing or pulling a cat from a hiding place.']];const symbols={eye:'◉',wave:'〰',paw:paw,moon:'☾'};return `<section class="section meet-section wrap" id="meet">${sectionHeading('Một lời chào,<br><em>theo cách của mèo.</em>','A little hello,<br><em>on their terms.</em>','HIỂU MÈO ĐỂ GẦN MÈO HƠN','UNDERSTANDING MAKES ROOM FOR CONNECTION')}<div class="meet-grid">${items.map(([icon,v,e,bv,be])=>`<article class="meet-card reveal"><div class="meet-icon">${symbols[icon]}</div><h3>${t(v,e)}</h3><p>${t(bv,be)}</p></article>`).join('')}</div></section>`;}
function storyCards(limit=3){return `<div class="stories-grid" data-blog-list="${limit}">${stories.map(s=>`<article class="story-card reveal"><a class="story-card-image" href="${href('chuyen-catfe/'+s.slug+'/')}">${image(s.image,s.title.vi,s.title.en)}<span class="image-arrow">${arrow}</span></a>${eyebrow(s.category.vi,s.category.en)}<h3><a href="${href('chuyen-catfe/'+s.slug+'/')}">${tt(s.title)}</a></h3><p>${tt(s.excerpt)}</p></article>`).join('')}</div>`;}
function storySection(){return `<section class="section stories-section"><div class="wrap"><div class="section-row">${sectionHeading('Những chuyện nhỏ.<br><em>Ở một nhà nhiều mèo.</em>','Little stories.<br><em>From a home full of cats.</em>','STORIES FROM CATFE','STORIES FROM CATFE')}${link('chuyen-catfe/','Xem thêm chuyện CATFE','More CATFE stories')}</div>${storyCards()}</div></section>`;}
function faqBlock(limit=8){return `<div class="faq-list">${faqs.slice(0,limit).map(([v,e,bv,be])=>`<details class="faq-item reveal"><summary>${t(v,e)}<span class="faq-plus" aria-hidden="true">+</span></summary><div class="faq-answer"><p>${t(bv,be)}</p></div></details>`).join('')}</div>`;}
function faqSection(){return `<section class="section faq-section wrap" id="faq"><div class="faq-heading reveal">${eyebrow('MỘT CHÚT TRƯỚC KHI GHÉ','A LITTLE SOMETHING BEFORE YOU VISIT')}<h2>${t('Bạn cứ hỏi.<br><em>Tụi mình ở đây.</em>','Curious?<br><em>We’re here.</em>')}</h2><p>${t('Một vài điều để buổi ghé đầu tiên nhẹ tênh.','A few details to help your first visit feel easy.')}</p>${external('https://www.facebook.com/catfevn/','Hỏi CATFE trên Facebook','Message CATFE on Facebook')}${catDrawing}</div>${faqBlock()}</section>`;}
function eventCards(){return `<div class="events-grid">${events.map(e=>`<article class="event-card reveal">${image(e.image,e.title.vi,e.title.en)}<div>${eyebrow(e.dateLabel.vi,e.dateLabel.en)}<h3>${tt(e.title)}</h3><p>${tt(e.description)}</p>${external(e.url,'Xem chi tiết','Details')}</div></article>`).join('')}</div>`;}
function eventsSection(){return events.length?`<section class="section events-section wrap" id="events">${sectionHeading('Sắp tới, ở nhà mèo.','Coming up at CATFE.','NHỮNG BUỔI HẸN ĐÃ CÓ LỊCH','DATES FOR YOUR DIARY')}${eventCards()}</section>`:'';}
function partnerSection(){return partners.length?`<section class="section wrap partners-section">${sectionHeading('Những người bạn của CATFE.','Friends of CATFE.','CÙNG CHĂM MỘT NGÔI NHÀ','CARING FOR A HOME, TOGETHER')}<div class="partner-grid">${partners.map(p=>`<article>${image(p.image,p.name,p.name)}${eyebrow(p.role.vi,p.role.en)}<h3>${esc(p.name)}</h3><p>${tt(p.description)}</p>${external(p.url,'Tìm hiểu thêm','Meet our partner')}</article>`).join('')}</div></section>`:'';}
function hero(){const heroImage=fs.existsSync(path.join(publicDir,'assets','hero-lounge.jpg'))?'hero-lounge.jpg':branchImage(branches[0]);return `<section class="hero"><div class="hero-backdrop">${image(heroImage,'Không gian thật và những bé mèo tại CATFE','The café and its cats at CATFE','',true)}</div><div class="hero-shade"></div><div class="hero-inner wrap"><div class="hero-copy">${eyebrow('CATFE · THIÊN ĐƯỜNG MÈO TỪ 2016','CATFE · A LITTLE CAT PARADISE SINCE 2016')}<h1>${t('Ghé một chút.<br><em>Nhớ một bé.</em>','Stay a while.<br><em>Remember a cat.</em>')}</h1><p>${t('Một quán cà phê mèo để ngồi lại, làm quen với những bé có tính cách rất riêng.','A cat café to settle into, with distinct little personalities to become familiar with.')}</p><div class="hero-buttons">${link('cac-nha/','Chọn nhà CATFE','Find your CATFE','button')}${link('lan-dau-ghe/','Lần đầu ghé?','Your first visit?','text-link light-link')}</div><div class="hero-footnote">${paw}${t('3 nhà tại Sài Gòn · Buffet đã gồm trong vé','3 homes in Saigon · Snacks and drinks included')}</div></div><div class="hero-cats" aria-label="Những khoảnh khắc CATFE / CATFE moments"><figure class="cat-snapshot snapshot-big" data-tilt>${image('hero.jpg','Một bé mèo Bengal tại CATFE','A Bengal cat at CATFE','',true)}<figcaption>${t('meo. bạn tới rồi!','meow. you made it!')}</figcaption></figure><figure class="cat-snapshot snapshot-small" data-tilt>${image('mischief.jpg','Một bé mèo CATFE mặc bộ đồ vịt vàng','A CATFE cat wearing a yellow duck outfit','',true)}<figcaption>${t('mỗi bé, một tính.','a character of their own.')}</figcaption></figure><figure class="cat-snapshot snapshot-family">${image('estella-banner.jpg','Những bé mèo quây quần tại CATFE Estella','Cats gathering at CATFE Estella','',true)}<figcaption>${t('cả hội nhiều ria.','the whisker club.')}</figcaption></figure><div class="hero-stamp">${paw}<span>${t('chậm lại<br>một chút nhé.','a little<br>less rush.')}</span></div></div></div><a class="scroll-cue" href="#reasons"><span>${t('Còn nhiều chuyện dễ thương phía dưới','More little cat moments below')}</span>↓</a></section>`;}
function pageIntro(v,e,subV,subE,eyV='CATFE · THIÊN ĐƯỜNG MÈO',eyE='CATFE · A LITTLE CAT PARADISE'){return `<section class="page-intro wrap reveal">${eyebrow(eyV,eyE)}<h1>${t(v,e)}</h1>${subV?`<p>${t(subV,subE)}</p>`:''}</section>`;}
function home(){return hero()+`<div class="ribbon" aria-hidden="true"><div>${Array.from({length:4},()=>`<span>${t('mỗi bé một tính','every cat a character')}</span>${paw}<span>${t('mỗi lần ghé một niềm vui','every visit a little joy')}</span>${paw}`).join('')}</div></div>`+reasons()+storyIntro()+proof()+steps()+eventsSection()+locations()+meet()+collars()+storySection()+partnerSection()+faqSection()+closing();}
function branchPage(b){return `<section class="branch-hero"><div class="branch-cover">${image(branchImage(b),'Không gian CATFE '+b.name,'CATFE '+b.name,'',true)}</div><div class="branch-hero-copy wrap">${eyebrow('NHÀ CATFE · '+b.no,'CATFE HOME · '+b.no)}<h1>${b.name}</h1><p>${tt(b.label)}</p></div></section><section class="section wrap branch-layout"><div class="branch-main reveal"><a class="breadcrumb" href="${href('cac-nha/')}">← ${t('Các nhà CATFE','Our homes')}</a><h2>${t('Một nhà mèo.<br><em>Một buổi của bạn.</em>','A home full of cats.<br><em>An afternoon for you.</em>')}</h2><p class="lead">${tt(b.note)}</p><p>${t('Buffet đồ ăn vặt và nước uống đã gồm trong vé. Không giới hạn thời gian trong giờ hoạt động — bạn có thể thong thả quan sát và làm quen.','The snack and drink buffet is included in your ticket. There’s no time limit during café hours, so you can settle in and meet the cats at an easy pace.')}</p>${residents.callout(b)}</div><aside class="visit-card reveal"><span class="visit-card-paw">${paw}</span>${eyebrow('LÊN LỊCH MỘT BUỔI GHÉ','PLAN A LITTLE CAT DATE')}<h3>${b.name}</h3><dl><div><dt>${t('Địa điểm','Location')}</dt><dd>${tt(b.address)}</dd></div><div><dt>${t('Giờ đón khách','Café hours')}</dt><dd>10:00–21:30</dd></div><div><dt>${t('Vé / người','Ticket / guest')}</dt><dd>${tt(b.price)}</dd></div></dl>${external('https://www.facebook.com/catfevn/','Nhắn CATFE','Message CATFE','button')}${external('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(b.map),'Xem đường đi','Directions','button button-outline')}<button class="copy-address text-link" type="button" data-copy-vi="${esc(b.name+' — '+b.address.vi.replace('<br>',' · '))}" data-copy-en="${esc(b.name+' — '+b.address.en.replace('<br>',' · '))}">${t('Sao chép địa chỉ','Copy address')}</button><small>${t('Nhắn quán để xác nhận trước khi ghé vào dịp lễ hoặc đi theo nhóm.','Confirm holiday or group arrangements with the café before visiting.')}</small></aside></section>`+meet()+`<section class="section wrap other-homes"><h2>${t('Hay ghé một nhà khác?','Another CATFE home?')}</h2><div class="other-home-links">${branches.filter(x=>x.slug!==b.slug).map(x=>link(x.slug+'/',x.name,x.name,'button button-outline')).join('')}</div></section>`;}
function memberPage(b){const members=cats[b.slug]||[];if(members.length)return residents.index(b);const intro=pageIntro('Các bé nhà <em>'+b.short+'.</em>','The cats of <em>'+b.short+'.</em>','Mỗi bé một gương mặt. Mỗi bé một cách làm quen.','Different little faces. Different ways to become friends.','THÀNH VIÊN · '+b.name,'RESIDENTS · '+b.name);if(!members.length)return intro+`<section class="coming-soon wrap"><div class="coming-art reveal">${catDrawing}<span class="floating-paw p1">${paw}</span><span class="floating-paw p2">${paw}</span><span class="coming-small">meo…</span></div><div class="coming-copy reveal"><span class="pill">Coming soon</span><h2>${t('Cả nhà sắp<br><em>lên hình.</em>','The family’s<br><em>on its way.</em>')}</h2><p>${t('Ảnh, tên và tính cách từng bé đang chờ được giới thiệu. Khi trang thành viên sẵn sàng, bạn sẽ có thể chọn từng bé để đọc câu chuyện riêng.','Photos, names and personalities are waiting to be introduced. When the residents’ page is ready, you’ll be able to explore each cat’s own story.')}</p>${link(b.slug+'/','Xem thông tin nhà '+b.short,'Explore the '+b.short+' home','button')}${link('cac-nha/','Xem các nhà CATFE','All CATFE homes')}</div></section>`;}
function catPage(b,c){return residents.profile(b,c);}

function storyPage(){return pageIntro('Chuyện của một<br><em>ngôi nhà nhiều mèo.</em>','Stories from<br><em>a home full of cats.</em>','Có những bé đã lớn lên và già đi cùng CATFE. Có những câu chuyện bắt đầu từ một lần ngồi lại.','Some cats have grown up and grown older with CATFE. Some stories begin by simply sitting down.')+storyIntro()+proof()+`<section class="section wrap blog-index"><div class="blog-list-heading"><h2>${t('Chuyện mới ở nhà mèo.','From the cat café journal.')}</h2></div>${storyCards(0)}</section>`+closing();}
function articlePage(s){return `<article class="story-article wrap"><div class="article-heading reveal"><a class="breadcrumb" href="${href('chuyen-catfe/')}">← ${t('Chuyện CATFE','CATFE stories')}</a>${eyebrow(s.category.vi,s.category.en)}<h1>${tt(s.title)}</h1><p class="lead">${tt(s.excerpt)}</p></div><div class="article-layout"><figure class="article-photo reveal">${image(s.image,'Ảnh từ CATFE — '+s.title.vi,'A photograph from CATFE — '+s.title.en,'',true)}<figcaption>${t('Một khoảnh khắc thật, từ CATFE.','A real moment, photographed at CATFE.')}</figcaption></figure><div class="prose reveal">${s.paragraphs.map(p=>`<p>${tt(p)}</p>`).join('')}${s.source?external(s.source,'Đọc chia sẻ gốc của CATFE','Read CATFE’s original story'):''}<div class="article-next">${link('cac-nha/','Hẹn một buổi ở nhà mèo','Plan a CATFE visit','button')}</div></div></div></article>`+`<section class="section stories-section"><div class="wrap">${sectionHeading('Một chuyện nhỏ nữa nhé.','One more little story.','CHUYỆN CATFE','CATFE STORIES')}${storyCards()}</div></section>`;}
function firstPage(){return pageIntro('Lần đầu ghé.<br><em>Cứ thấy như ở nhà.</em>','First time here.<br><em>Make yourself at home.</em>','Bạn chưa cần biết làm quen với mèo thế nào. Bắt đầu bằng chọn một nhà và để nhân viên hướng dẫn.','You don’t need to know every cat’s ways already. Choose a home and let the team guide you.')+steps()+meet()+collars()+`<section class="section first-photo-section"><div class="wrap split-banner"><div>${image('together.jpg','Khách ngồi chơi cùng mèo tại CATFE','Guests spending time with cats at CATFE')}</div><div>${eyebrow('VÀI ĐIỀU NHO NHỎ','LITTLE DETAILS THAT MATTER')}<h2>${t('Nhẹ tay.<br><em>Nhẹ cả một buổi.</em>','Gentle hands.<br><em>An easy afternoon.</em>')}</h2><ul class="care-list"><li>${t('Rửa tay trước khi làm quen.','Clean your hands before meeting the cats.')}</li><li>${t('Không dùng flash, không rượt đuổi.','Avoid flash photography and chasing.')}</li><li>${t('Không cho mèo ăn đồ của người.','Keep human food away from cats.')}</li><li>${t('Hỏi nhân viên trước khi bế hoặc cho ăn.','Ask the team before holding or feeding a cat.')}</li></ul>${link('cac-nha/','Chọn nhà để ghé','Choose a home','button')}</div></div></section>`+faqSection();}
function eventPage(){return pageIntro('Những cuộc hẹn<br><em>ở nhà mèo.</em>','Little gatherings<br><em>at the cat café.</em>','Lịch những hoạt động được CATFE xác nhận sẽ có mặt tại đây.','Confirmed CATFE gatherings will appear here.','EVENTS AT CATFE','EVENTS AT CATFE')+`<section class="section wrap">${events.length?eventCards():`<div class="event-empty reveal"><div class="event-symbol">${paw}</div><h2>${t('Chưa có lịch hẹn mới.','No dates announced just yet.')}</h2><p>${t('Trong lúc chờ tin từ nhà mèo, bạn vẫn có thể ghé chơi như thường lệ. Nếu muốn tổ chức một buổi ghé theo nhóm, nhắn CATFE để hỏi trước nhé.','While you wait for the next café update, you can still plan an everyday visit. For a group gathering, message CATFE to discuss arrangements.')}</p><div class="empty-actions">${link('cac-nha/','Chọn nhà CATFE','Find your CATFE','button')}${external('https://www.facebook.com/catfevn/','Theo dõi tin từ CATFE','Follow CATFE updates')}</div></div>`}</section>`;}
function shell(content,titleVi,titleEn,description){return `<!doctype html><html lang="vi" id="top"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#382214"><title>${esc(titleVi)}</title><meta name="description" content="${esc(description)}"><meta property="og:title" content="${esc(titleVi)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><link rel="icon" href="${asset('logo.png')}"><link rel="stylesheet" href="${asset('fonts.css')}"><link rel="stylesheet" href="${href('style.css')}"><link rel="stylesheet" href="${href('members.css')}"><script src="${href('translations.js')}" defer></script><script src="${href('app.js')}" defer></script><script src="${href('blog.js')}" defer></script><script src="${href('analytics.js')}" defer></script></head><body data-title-vi="${esc(titleVi)}" data-title-en="${esc(titleEn)}">${header()}<main id="main">${content}</main>${footer()}<div class="toast" role="status" aria-live="polite"></div><noscript><p class="noscript-note">Nội dung tiếng Việt có sẵn. Bật JavaScript để chuyển sang tiếng Anh. Enable JavaScript to switch to English.</p></noscript></body></html>`;}
function write(route,titleVi,titleEn,build){currentPage=route;const content=build();let html=shell(content,titleVi,titleEn,'CATFE — Thiên đường mèo tại Sài Gòn. Chọn nhà Tân Phú, Bình Tân hoặc Estella, tìm hiểu chuyến ghé đầu tiên và làm quen với các bé.');let linkNo=0;html=html.replace(/<a\b([^>]*)>/g,(_,attrs)=>`<a${attrs} data-track-id="${route.replaceAll('/','_').replace('.html','')}.link.${linkNo++}">`);const dest=path.join(out,route);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,html);}

write('index.html','CATFE — Ghé một chút. Nhớ một bé.','CATFE — Stay a while. Remember a cat.',home);
write('cac-nha/index.html','Các nhà CATFE — Tân Phú · Bình Tân · Estella','CATFE homes — Tân Phú · Bình Tân · Estella',()=>pageIntro('Chọn một nhà.<br><em>Hẹn một buổi.</em>','Choose a home.<br><em>Plan an afternoon.</em>','Ba địa điểm tại Sài Gòn. Mỗi nhà một gia đình mèo để bạn làm quen.','Three locations in Saigon. Each with its own little cat family to meet.')+`<section class="section locations all-locations"><div class="wrap">${locationCards()}<p class="location-note">${t('Chi nhánh Quận 1 đã đóng từ 01/03/2026. Hẹn gặp bạn tại ba nhà trên.','The District 1 location closed on 1 March 2026. We look forward to seeing you at these three homes.')}</p></div></section>`+closing());
write('chuyen-catfe/index.html','Chuyện CATFE — Một nhà nhiều mèo','CATFE stories — A home full of cats',storyPage);
write('lan-dau-ghe/index.html','Lần đầu ghé CATFE','Your first CATFE visit',firstPage);
write('events/index.html','Events — Những cuộc hẹn ở CATFE','Events — Little CATFE gatherings',eventPage);
write('faq/index.html','FAQ — Những điều bạn muốn biết về CATFE','FAQ — Before your CATFE visit',()=>pageIntro('Bạn cứ hỏi.<br><em>Tụi mình ở đây.</em>','Ask away.<br><em>We’re here.</em>','Thông tin cho một buổi ghé nhẹ nhàng, từ vé tới cách làm quen với mèo.','Details for an easy visit, from tickets to meeting the cats.')+`<section class="section wrap standalone-faq">${faqBlock()}<div class="faq-contact"><p>${t('Còn điều gì riêng cho chuyến ghé của bạn?','Anything else about your visit?')}</p>${external('https://www.facebook.com/catfevn/','Nhắn CATFE','Message CATFE','button')}</div></section>`);
for(const b of branches){write(b.slug+'/index.html',b.name+' — Nhà CATFE',b.name+' — A CATFE home',()=>branchPage(b));write(b.slug+'/cats/index.html','Các bé '+b.short+' — CATFE',b.short+' cats — CATFE',()=>memberPage(b));for(const c of cats[b.slug]||[]){if(!/^[a-z0-9-]+$/.test(c.slug))throw new Error('Invalid cat slug');write(b.slug+'/cats/'+c.slug+'/index.html',c.name+' — CATFE '+b.short,c.name+' — CATFE '+b.short,()=>catPage(b,c));}}
for(const s of stories)write('chuyen-catfe/'+s.slug+'/index.html',s.title.vi+' — CATFE',s.title.en+' — CATFE',()=>articlePage(s));
write('blog/template/index.html','Chuyện CATFE','CATFE stories',()=>'<article class="dynamic-article wrap"><!--BLOG_CONTENT--></article>'+closing());
write('404.html','Mèo đi lạc rồi — CATFE','A little wrong turn — CATFE',()=>pageIntro('Hình như mình<br><em>rẽ nhầm một chút.</em>','A little<br><em>wrong turn.</em>','Không sao, các nhà CATFE vẫn ở đây.','The CATFE homes are still right here.')+`<section class="section wrap error-page">${catDrawing}${link('','Về trang chủ','Back to the café','button')}${link('cac-nha/','Chọn nhà CATFE','Find your CATFE')}</section>`);
fs.mkdirSync(path.join(out,'quan-tri'),{recursive:true});fs.copyFileSync(path.join(root,'site','admin.html'),path.join(out,'quan-tri','index.html'));fs.rmSync(path.join(publicDir,'admin.html'),{force:true});
fs.writeFileSync(path.join(publicDir,'translations.js'),'window.CATFE_TRANSLATIONS = '+JSON.stringify(strings)+';\n');
fs.writeFileSync(path.join(root,'content','seed-stories.json'),JSON.stringify(stories.map((s,i)=>({id:'seed-'+s.slug,slug:s.slug,content:{titleVi:s.title.vi,titleEn:s.title.en,excerptVi:s.excerpt.vi,excerptEn:s.excerpt.en,bodyVi:s.paragraphs.map(p=>p.vi).join('\n\n'),bodyEn:s.paragraphs.map(p=>p.en).join('\n\n'),cover:'/assets/'+s.image,altVi:s.title.vi,altEn:s.title.en,category:['moments','visits','care'][i],branch:'all'}})),null,2));
const fonts=path.join(publicDir,'assets','fonts.css');fs.writeFileSync(fonts,fs.readFileSync(fonts,'utf8').replaceAll('/assets/','./'));
console.log('Built presentation pages plus '+Object.values(cats).flat().length+' cat profiles. '+Object.keys(strings).length+' bilingual strings.');
